### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by joehoeller** [getredash/contrib-helm-chart#66]
Error:

`Failed to install app redash. Error: failed post-install: warning: Hook post-install redash/templates/hook-install-job.yaml failed: jobs.batch "redash-install" already exists`

And logs...

```
Using external postgresql database 
Using Redis: redis://:******@redash-redis-master:6379/0 
[2020-12-24 00:48:26 +0000] [6] [INFO] Starting gunicorn 19.7.1 
[2020-12-24 00:48:26 +0000] [6] [INFO] Listening at: http://0.0.0.0:5000 (6) 
[2020-12-24 00:48:26 +0000] [6] [INFO] Using worker: sync 
[2020-12-24 00:48:26 +0000] [10] [INFO] Booting worker with pid: 10 
[2020-12-24 00:48:26 +0000] [12] [INFO] Booting worker with pid: 12 
[2020-12-24 00:48:27 +0000] [14] [INFO] Booting worker with pid: 14 
[2020-12-24 00:48:27 +0000] [16] [INFO] Booting worker with pid: 16 
[2020-12-24 00:48:41,499] ERROR in app: Exception on /ping [GET] 
Traceback (most recent call last): 
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app 
    response = self.full_dispatch_request() 
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1607, in full_dispatch_request 
    self.try_trigger_before_first_request_functions() 
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1654, in try_trigger_before_first_request_functions 
    func() 
  File "/app/redash/version_check.py", line 85, in reset_new_version_status 
    latest_version = get_latest_version() 
  File "/app/redash/version_check.py", line 91, in get_latest_version 
    return redis_connection.get(REDIS_KEY) 
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1264, in get 
    return self.execute_command('GET', name) 
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 772, in execute_command 
    connection = pool.get_connection(command_name, **options) 
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 994, in get_connection 
    connection.connect() 
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 497, in connect 
    raise ConnectionError(self._error_message(e)) 
ConnectionError: Error 111 connecting to redash-redis-master:6379. Connection refused. 
[2020-12-24 00:48:51,515] ERROR in app: Exception on /ping [GET] 
Traceback (most recent call last): 
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app 
    response = self.full_dispatch_request() 
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1607, in full_dispatch_request 
    self.try_trigger_before_first_request_functions() 
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1654, in try_trigger_before_first_request_functions 
    func() 
  File "/app/redash/version_check.py", line 85, in reset_new_version_status 
    latest_version = get_latest_version() 
  File "/app/redash/version_check.py", line 91, in get_latest_version 
    return redis_connection.get(REDIS_KEY) 
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1264, in get 
    return self.execute_command('GET', name) 
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 772, in execute_command 
    connection = pool.get_connection(command_name, **options) 
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 994, in get_connection 
    connection.connect() 
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 497, in connect 
    raise ConnectionError(self._error_message(e)) 
ConnectionError: Error 111 connecting to redash-redis-master:6379. Connection refused. 
[2020-12-24 00:49:00,496][PID:12][INFO][metrics] method=GET path=/ping endpoint=redash_ping status=200 content_type=text/html; charset=utf-8 content_length=5 duration=0.13 query_count=0 query_duration=0.00 
[2020-12-24 00:49:10,493][PID:12][INFO][metrics] method=GET path=/ping endpoint=redash_ping status=200 content_type=text/html; charset=utf-8 content_length=5 duration=0.11 query_count=0 query_duration=0.00 
[2020-12-24 00:49:20,496][PID:16][INFO][metrics] method=GET path=/ping endpoint=redash_ping status=200 content_type=text/html; charset=utf-8 content_length=5 duration=0.14 query_count=0 query_duration=0.00 
```

**Comment by joehoeller** [comment]
@jezdez  @arikfr  @ranbena  @yzorg  its happening again, is there a way to clear this out after deletion w/ kubectl?

**Comment by jezdez** [comment]
@joehoeller Please understand that this repo is maintained by the community and not the Redash maintainers. I would appreciate it if you wouldn't @ me. Thanks.

**Comment by joehoeller** [comment]
@jezdez  yeah thats fine, but this was 11 days old and no one ever answered it and the problem still persists. Have you seen this happen before?

**Comment by jezdez** [comment]
I don't use this repo and never have. I can't help you.

**Comment by joehoeller** [comment]
> I don't use this repo and never have. I can't help you.

Which repo do you use?

**Comment by TreeKat71** [comment]
For the `Failed to install app redash. Error: failed post-install: warning: Hook post-install redash/templates/hook-install-job.yaml failed: jobs.batch "redash-install" already exists` part
Run `kubectl get all` and then delete job related to this chart like `kubectl delete job.batch/my-release-install`

You may need to `kubectl get pvc` and delete them. Delete the chart and remove all stuff and install it again.
