### ISSUE TITLE
Redis password is mandatory

### ISSUE THREAD

**Issue by francoisminaud** [getredash/contrib-helm-chart#71]
Redis password should be mandatory in the values manifest.

It actually will not prevent the chart to be installed the first time. However upon updating the chart and installing (upgrading) the application,the main dash worker will fail:

2021-01-27 14:48:25,434] ERROR in app: Exception on /login [GET]
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
     response = self.full_dispatch_request()
   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
     return original_handler(e)
   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
     rv = self.preprocess_request()
   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
     rv = func()
   File "/usr/local/lib/python2.7/site-packages/flask_limiter/extension.py", line 400, in __check_request_limit
     six.reraise(*sys.exc_info())
   File "/usr/local/lib/python2.7/site-packages/flask_limiter/extension.py", line 365, in __check_request_limit
     if not self.limiter.hit(lim.limit, lim.key_func(), limit_scope):
   File "/usr/local/lib/python2.7/site-packages/limits/strategies.py", line 132, in hit
     self.storage().incr(item.key_for(*identifiers), item.get_expiry())
   File "/usr/local/lib/python2.7/site-packages/limits/storage.py", line 446, in incr
     return self.lua_incr_expire([key], [expiry])
   File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 3575, in __call__
     return client.evalsha(self.sha, len(keys), *args)
   File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2761, in evalsha
     return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
   File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 772, in execute_command
     connection = pool.get_connection(command_name, **options)
   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 994, in get_connection
     connection.connect()
   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 502, in connect
     self.on_connect()
   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 570, in on_connect
     if nativestr(self.read_response()) != 'OK':
   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 642, in read_response
     raise response
 ResponseError: WRONGPASS invalid username-password pair

This is due to Redis password not set and changed by Helm upon the second installation. 
Setting it prevents this behaviour.

**Comment by ukd1** [comment]
@francoisminaud thanks for this - just hit this issue myself
