### ISSUE TITLE
Error when I execute a query 

### ISSUE THREAD

**Issue by JooyoungJeong** [getredash/contrib-helm-chart#8]
Hi. 

I changed tag: 8.0.1.b33387
and helm install. 

I added datasource for mysql . and I can see table in mysql 

But. i got the error when i execute a query. 

How can I setup for tag: 8.0.1.b33387 version.  ?

$ kubectl logs redash-adhocworker-578696f94b-b6nhc      
```
[2019-11-29 07:01:50,071][PID:166][INFO][ForkPoolWorker-138] task_name=redash.tasks.execute_query task_id=09521991-c4f9-4da5-8eb8-be6a58385b59 task=execute_query state=load_ds ds_id=1
[2019-11-29 07:01:50,271][PID:166][ERROR][ForkPoolWorker-138] Task redash.tasks.execute_query[09521991-c4f9-4da5-8eb8-be6a58385b59] raised unexpected: InvalidToken()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/redash/worker.py", line 84, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/redash/tasks/queries.py", line 436, in execute_query
    scheduled_query).run()
  File "/app/redash/tasks/queries.py", line 339, in __init__
    self.data_source = self._load_data_source()
  File "/app/redash/tasks/queries.py", line 422, in _load_data_source
    return models.DataSource.query.get(self.data_source_id)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 924, in get
    ident, loading.load_on_pk_identity)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 1007, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 250, in load_on_pk_identity
    return q.one()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2954, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2924, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 98, in instances
    util.raise_from_cause(err)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 79, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 511, in _instance
    loaded_instance, populate_existing, populators)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 611, in _populate_full
    dict_[key] = getter(row)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 1226, in process
    return process_value(impl_processor(value), dialect)
  File "/app/redash/models/types.py", line 28, in process_result_value
    return ConfigurationContainer.from_json(super(EncryptedConfiguration, self).process_result_value(value, dialect))
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 409, in process_result_value
    decrypted_value = self.engine.decrypt(value)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 216, in decrypt
    decrypted = self.fernet.decrypt(value)
  File "/usr/local/lib/python2.7/site-packages/cryptography/fernet.py", line 75, in decrypt
    return self._decrypt_data(data, timestamp, ttl)
  File "/usr/local/lib/python2.7/site-packages/cryptography/fernet.py", line 119, in _decrypt_data
    self._verify_signature(data)
  File "/usr/local/lib/python2.7/site-packages/cryptography/fernet.py", line 108, in _verify_signature
    raise InvalidToken
InvalidToken
[2019-11-29 07:01:51,025][PID:6][INFO][MainProcess] Received task: redash.tasks.record_event[46dff3bc-39ac-4ff2-b75d-264a9d902508]  
[2019-11-29 07:01:51,032][PID:165][INFO][ForkPoolWorker-137] Task redash.tasks.record_event[46dff3bc-39ac-4ff2-b75d-264a9d902508] succeeded in 0.00644092302537s: None
[2019-11-29 07:01:57,699][PID:6][INFO][MainProcess] Received task: redash.tasks.refresh_queries[8e537b40-aa25-4eb4-a5c9-13c6a3146008]  
```

Thank you.

**Comment by JooyoungJeong** [comment]
https://github.com/getredash/redash/issues/3761

 I add REDASH_COOKIE_SECRET in env for redash-adhocworker  and redash-scheduledworker

```
env:
        - name: REDASH_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: cookieSecret
              name: redash
```
